feature/add-monitoring-disable-plan-for-prometheus
EncoreTechnologies/puppet-patching pull request #71
Opened 2020-12-03 14:23 UTC by jschoewe

Added bolt plan to enable/disable monitoring in prometheus by changing a puppet fact on the node. Also added script to refresh Prometheus targets from puppetdb with the matching fact and prometheus resource

2020-12-10 15:41 UTC, nmaludy requested changes

2020-12-10 15:41 UTC, nmaludy commented on tasks/monitoring_prometheus.py
> +class PrometheusAlertSilence(TaskHelper):
This should be written in Ruby like the other HTTP code is

2020-12-10 15:41 UTC, nmaludy commented on plans/monitoring_solarwinds_prometheus.pp
> +  run_plan('patching::monitoring_solarwinds', $targets,
I expected a plan that is generic like we talked about, not hard coded for SolarWinds + Prometheus.

2020-12-16 14:13 UTC, nmaludy commented on metadata.json
> +  "version": "1.2.1",
should be version 1.2.0, right?

2020-12-16 14:17 UTC, nmaludy commented on plans/monitoring_multiple.pp
> +  Array                     $monitoring_plan = get_targets($targets)[0].vars['patching_monitoring_plan'],
you're going to need to use a different key here

2020-12-16 14:18 UTC, nmaludy requested changes

2020-12-16 14:18 UTC, nmaludy commented on plans/monitoring_multiple.pp
> +}
missing newline at end of the file

2020-12-16 14:22 UTC, nmaludy commented on plans/monitoring_multiple.pp
> +  Array                     $monitoring_plan = get_targets($targets)[0].vars['patching_monitoring_plan'],
if you use `patching_monitoring_plan` as an array, it's going to fail when you call `bolt plan run patching`.

Instead this key should be something like `patching_monitoring_plan_multiple` or similar.

Your vars would then look like:
```
vars:
  patching_monitoring_plan: 'patching::monitoring_multiple'
  patching_monitoring_plan_multiple:
    - 'patching::monitoring_solarwinds'
    - 'patching::monitoring_prometheus'
 ```

2021-01-13 21:10 UTC, nmaludy approved these changes

2021-01-13 21:11 UTC, nmaludy commented
@jschoewe i think you just need to get build to pass

2021-01-19 14:50 UTC, bishopbm1 commented
@nmaludy can this be merged?

2021-01-19 15:47 UTC, merged