Add OracleLinux support
EncoreTechnologies/puppet-patching pull request #83
Opened 2021-06-15 19:39 UTC by seanmil

Correctly detect/parse OS_RELEASE on OracleLinux and include OL
as a RHEL-compatible OS.

2021-06-15 19:42 UTC, nmaludy requested changes
@seanmil could you please add a CHANGELOG entry here. Otherwise looks good! https://github.com/EncoreTechnologies/puppet-patching/blob/master/CHANGELOG.md

2021-07-07 15:14 UTC, nmaludy commented
@seanmil could you please merge in the latest changes and we can get this pulled in?

Thanks!

2021-07-08 15:04 UTC, seanmil commented
> @seanmil could you please merge in the latest changes and we can get this pulled in?

@nmaludy Done, sorry I didn't fix it up earlier. It fell off my plate. Thanks!

2021-07-08 15:40 UTC, nmaludy approved these changes

2021-07-08 15:40 UTC, merged